### PR TITLE
Update modifier manager to 3.22 capabilities

### PR DESCRIPTION
**Pull request by jrjohnson**
I started with updating the ember-cli version and then split the modifier manager into different classes based on the API difference in Ember 3.22+. This seemed like the cleaner path forward until support for 3.20-lts goes away.

I can split this up into different PRs or squash things a bit more, but wanted to check and see if this approach would work for you first.

### CODE REVIEW

**Comment by jrjohnson** [comment]
Just checking in @gmurphey to see if you want to move forward with this, or go another way.

**Comment by chancancode** [comment]
IMO this should just depend on https://github.com/ember-modifier/ember-modifier instead of using the low-level API which would resolve this issue once and for all (more or less).

**Comment by chancancode** [comment]
In https://github.com/emberjs/ember-inspector/pull/1793 I attempted to port this over to using ember-modifier and simplify things a bit along the way.

**Comment by jrjohnson** [comment]
Would recommend [ember-on-resize-modifier](https://www.npmjs.com/package/ember-on-resize-modifier) as a replacement. Going to close this.

**Pull request closed without merging**
